createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: group
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .path
          title: .name
          blueprint: '"gitlabGroup"'
          properties:
            visibility: .visibility
            url: .web_url
            description: .description

  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .path_with_namespace | gsub(" "; "")
          title: ".name"
          blueprint: '"project"'
          properties:
            url: .web_url
            readme: file://README.md
            description: .description
            language: .language
            namespace: .namespace.name
            fullPath: .namespace.full_path
            defaultBranch: .default_branch
          relations:
            group: .namespace.path

  - kind: merge-request
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .iid | tostring
          title: .title
          blueprint: '"gitlabMergeRequest"'
          properties:
            creator: .author.username
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .web_url
            reviewers: .reviewers[].username
          relations:
            service: '.web_url | split("/") | .[3] + "/" + .[4]'

  - kind: issue
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.web_url | split("/") | .[3] + "/" + .[4] + "/" + (.iid | tostring)'
          title: ".title"
          blueprint: '"gitlabIssue"'
          properties:
            link: .web_url
            description: .description
            createdAt: .created_at
            closedAt: .closed_at
            updatedAt: .updated_at
            creator: .author.username
            status: .state
            labels: .labels
          relations:
            service: '.web_url | split("/") | .[3] + "/" + .[4]'
